apiVersion: v1
kind: Namespace
metadata:
  name: playlist-sync
  labels:
    app.kubernetes.io/managed-by: flux
    name: playlist-sync
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "disabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
  labels:
    app.kubernetes.io/managed-by: flux
    name: cloudflare
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "disabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: infisticaleso
  labels:
    app.kubernetes.io/managed-by: flux
    name: infisticaleso
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "disabled"
