apiVersion: v1
kind: Namespace
metadata:
  name: playlist-sync
  labels:
    app.kubernetes.io/managed-by: flux
    name: playlist-sync
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
  labels:
    app.kubernetes.io/managed-by: flux
    name: cloudflare
---
apiVersion: v1
kind: Namespace
metadata:
  name: infisticaleso
  labels:
    app.kubernetes.io/managed-by: flux
    name: infisticaleso
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/managed-by: flux
    name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    app.kubernetes.io/managed-by: flux
    name: sealed-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: lifebuddies
  labels:
    app.kubernetes.io/managed-by: flux
    name: lifebuddies
---
apiVersion: v1
kind: Namespace
metadata:
  name: misc
  labels:
    app.kubernetes.io/managed-by: flux
    name: misc
