apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-managed-secrets
  namespace: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store

  refreshPolicy: Periodic
  refreshInterval: 1h

  target:
    name: cloudflare-tunnel-token

  dataFrom:
    - find:
        name:
          regexp: .*
