---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: playlist-sync-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/Ozoniuss/playlist-sync
  ref:
    branch: main
