---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: playlist-sync-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Ozoniuss/playlist-sync
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: playlist-sync
  namespace: playlist-sync
spec:
  interval: 1m
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  suspend: true
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: playlist-sync-charts
        namespace: flux-system
  values:
    cronjob:
      schedule: "0 6 * * *"
  valuesFrom:
    - kind: Secret
      name: playlist-sync-secret
      valuesKey: path
      targetPath: nfs.path
    - kind: Secret
      name: playlist-sync-secret
      valuesKey: storage
      targetPath: nfs.storage
    - kind: Secret
      name: playlist-sync-secret
      valuesKey: server
      targetPath: nfs.server
    - kind: Secret
      name: playlist-sync-secret
      valuesKey: youtube_api_key
      targetPath: youtubeApiKey
