---
# This is meant to be the only secret sealed via kubeseal, then we can install
# an operator to read secrets from infistical using these credentials.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infistical-auth-credentials
  namespace: infisticaleso
spec:
  encryptedData:
    clientId: AgBvAUcdC6Oyws4Eqg5f44WhLY/YrMpf5R8vW326QaEvmh1wscVvNo8DCN7jgk7CWrQCxnbu91ysguQzjQoZLbYyM+gGc2InBX/re+cf+PdGg/53b+4W8IHUABahqWSNUhYW+fW6uGLoeh6oEUs3yn6NQi3a+ByTWEWQLndwNA8zcpCiqJqWLVPj9BlYJp44t9SMW7TmrovfSyc9EbvYv4jiX4ekUSi+9y/nqCdd9dtyKD/k4SQP1+dZatWHVsVIhEXUGiHqhBXBTdkkJap7rbo1tINaNpKkI6QPiG7gqXdBx8EFH3dqS9phl1m12pedFv/58I8DucjR3T14zh9hLjvEa7XaXTEUy882VWnbklNLx+Is3I35gY8OpbbePWzbYqj/Mt3Y57wQWt/jTlhcB6XexfCoIwEWvDqLSP8YoEep/M33iTNpMdKtTyiH6Nc1QCNR8s5lc7LuURKvRxtKZyhGozvG3jgDK4u57QLO9hotoehUYltTNW0tKhfOmGID6Ozrwa60myoF/dnwnNSDbJR9fV/0Dlz8fTkpVSW3SxLnlfRrUmV0bS6EGHfLmmTQgYeXjNTIgnnH23+saY7UesrEYNd67+cBPJ59jgJt3wsbZxultZiKhQ5bKo7tjFnrfZ6z1aaebACG1MlTXLwlX9Rn6AB5Q9Jt+vDZtu9dS8hl2x65Ae34Bjzx4fg16Q5zWrELsXpabpL4lr4VnpRSLoGB7DmPfs7KNSWJ18JKEfeqHLaYg9s=
    clientSecret: AgCjhrF+TxhV00rMTJzGZnhj+/pZw7A82qxHRpOvHjvNlOyI1xa6M9W4eLZ//mgWLzC+nDtXTXWZckOWmjd3VzMj383rha5JjAI0d/QsUHjcnBmQPpPoDFXUW2ridZy2lwiqVSLul5IYrBx+cXBimlIkWIOVYMes6ykMyuBkrugiBRbifD00pojVYT5t6sZuSnFldA2MzFP6/jnFe4XtJuSHXRrMhlth1+MLQRKvYUQpIuvfenpzZh9oajWn2aXtBjJNwbeklnJDn28ziGyDHuPIBh3T2dOLvzMvy/5OCXCIuyj/uvyTOMBaluGcpwCzI+yXOEl5V4NgktrOMF90azYzRN8o3FsdCF2+kGerGgeW42JmzyQUnaJ5vuawjgJAmwiVg6ohlz7LRAJU7YIb+Wjf9FZJsWqf16MbbecXl3Mkhv/c/ZTaXwOnepOPSHHgNAcoFT1uLxJJVRTS/WNUYnaUKJKx8AfNX/1yl5bjJqitUhYfSYExazXSh7ClYYzmw9uuIFYvKQqEECPVMXjBDtoGNngpG+6vMbtru6gB5TdNiVerA83dFGmeuaxuc22Gyw2ALD753MZ5ilsYLIRhAPohXRCdtCAzlOwJ86oka695HQxv150Qccmpdbw5CoBsOrolLicDUTQNrZ3DGV7sq+EaS27w1Mf/FcsnekFnrpRFDrz7NNX0zg9SReBc5NB2XZOqqDk+hzQDpRcUj3TFi8YWD0VpBRpA5gh72AYvSRVpp6lI55X8Braom0erwKnFpWQfAuVLxETDB/qK0B9YMJok
  template:
    metadata:
      creationTimestamp: null
      name: infistical-auth-credentials
      namespace: infisticaleso
    type: Opaque
