apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoamiv2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: { app: whoamiv2 }
  template:
    metadata:
      labels: { app: whoamiv2 }
    spec:
      containers:
        - name: whoamiv2
          image: traefik/whoami:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoamiv2
  namespace: default
spec:
  type: NodePort
  selector:
    app: whoamiv2
  ports:
    - port: 80 # Service port inside cluster
      targetPort: 80 # Container port
      protocol: TCP
      nodePort: 31000 # Node port exposed on all nodes
